# Example services.yaml entry

delete:
  # Description of the service
  description: Delete google home timer or alarm.
  # Different fields that your service accepts
  fields:
    # Key of the field
    id:
      # Description of the field
      description: ID of timer or alarm (timer/xxx / alarm/xxx).
      # Example value that can be passed for this field
      example: "timer/adafhjdsljfsdkfjsdfnsdjlf"
